### ISSUE TITLE
Pkg creation 

### ISSUE THREAD

**Issue by albiii** [autopkg/crystalllized-recipes#7]
Google has changed the name of the package from GoogleFileStream.pkg to GoogleDrive.pkg the dmg name is still the same but the pkg recipe needs to be updated to reflect the new name of the package from google.

**Comment by albiii** [comment]
URLDownloader: Downloaded /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg
{'Output': {'download_changed': True,
            'etag': '"875a5e"',
            'last_modified': 'Tue, 23 Feb 2021 00:37:35 GMT',
            'pathname': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                        'Drive File Stream.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                                                                        'Drive '
                                                                        'File '
                                                                        'Stream.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/unpack/',
           'flat_pkg_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                            'Drive File Stream.dmg/GoogleDriveFileStream.pkg',
           'purge_destination': 'true'}}
FlatPkgUnpacker: Mounted disk image /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 171, in main
    f"No valid path found as given by 'flat_pkg_path': "
autopkglib.ProcessorError: No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg
Failed.
Receipt written to /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/receipts/DriveFS.jss-receipt-20210327-220029.plist

The following recipes failed:
    DriveFS.jss.recipe
        Error in local.jss.DriveFS: Processor: FlatPkgUnpacker: Error: No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg

The following new items were downloaded:
    Download Path                                                                                  
    -------------

**Comment by albiii** [comment]
URLDownloader: Downloaded /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg
{'Output': {'download_changed': True,
            'etag': '"875a5e"',
            'last_modified': 'Tue, 23 Feb 2021 00:37:35 GMT',
            'pathname': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                        'Drive File Stream.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                                                                        'Drive '
                                                                        'File '
                                                                        'Stream.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/unpack/',
           'flat_pkg_path': '/Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google '
                            'Drive File Stream.dmg/GoogleDriveFileStream.pkg',
           'purge_destination': 'true'}}
FlatPkgUnpacker: Mounted disk image /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 171, in main
    f"No valid path found as given by 'flat_pkg_path': "
autopkglib.ProcessorError: No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg
Failed.
Receipt written to /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/receipts/DriveFS.jss-receipt-20210327-220029.plist

The following recipes failed:
    DriveFS.jss.recipe
        Error in local.jss.DriveFS: Processor: FlatPkgUnpacker: Error: No valid path found as given by 'flat_pkg_path': /Users/autopkg/Library/AutoPkg/Cache/local.jss.DriveFS/downloads/Google Drive File Stream.dmg/GoogleDriveFileStream.pkg

The following new items were downloaded:
    Download Path                                                                                  
    -------------
